### ISSUE TITLE
Option to start browsing from current file location

### ISSUE THREAD

**Issue by Zyles** [danielfrg/sublime-open#2]
Most of the time when I want to quick open a file I want to open one that is near the one I am working on.

So it would be nice if you could add a bookmark that basically says "current directory of open file" so I can start browsing from there.

I tried using "." but that wouldn't work.

**Comment by danielfrg** [comment]
This was added on aa296cd63d8f2a5bf0a606efd568124f17a22726 by @dnalot. I will add a settings to make this optional and maybe play with some alternative UX in the next release.

**Comment by texastoland** [comment]
Speaking of `.` I started implementing it as either opening the current directory in a new window or adding it to the current project. Neither is straightforward. Opinion which? I'm leaning towards same window.

**Comment by danielfrg** [comment]
Not sure whats best until i try them but i believe in the same window would be the correct approach, the objective of the plugin is to fewer keystrokes.
